theopensystemslab/fairhold-dashboard

app/models/Household.ts, app/models/tenure/FairholdLandPurchase.test.ts, app/models/tenure/FairholdLandRent.test.ts
This PR updates the tests that were failing after I changed a few classes to enable interest rate spend & save calculations. Made a new one so as to keep PRs small. 
Uses my previous branch as a base!
I noticed that despite the good coverage we're seeing with Jest, a lot of the calculations aren't actually being tested, if I've understood everything correctly. That's probably something we want to rectify (especially since certain mortgage numbers are looking funky) so I have opened another card (see #122).
=> fix: update tests following interest calculation functionality

.gitignore, package-lock.json, package.json, typedoc.json
- Installs `typedoc` and `tsuml2` as dev dependencies
- Creates scripts (both run through `npm run docs`) to generate docs folder with a UML SVG in
- Adds the docs folder to the .gitignore
- As decided in the dev call, `typedoc-plugin-mermaid` wouldn't suit our case since we wanted the diagrams to be generated automatically; and having some sort of auto-generated map would be useful. 
- This gives us a crude SVG at the moment but should be able to be customised further. I'd like to also add it straight to the Typedocs HTML output but haven't gotten there yet! 
It may not be 100% ideal but hopefully it's useful for now?
Closes #121
=> feat: install Typedoc & class diagram library

app/api/route.test.ts, app/components/ui/CalculatorInput.tsx, app/components/ui/RadioButton.tsx, app/models/constants.ts, app/schemas/apiSchema.ts, app/schemas/calculationSchema.ts, app/schemas/formSchema.ts, app/services/calculationService.test.ts
Adds a radio button selector to the calculator form to select between maintenance spend levels. This PR has been rebased to create the selector with ShadCN.
=> feat: new maintenance selector

app/models/Fairhold.ts, app/models/ForecastParameters.ts, app/models/Household.ts, app/models/Lifetime.ts, app/models/Mortgage.ts, app/models/Property.ts, app/models/constants.ts, app/models/tenure/FairholdLandPurchase.ts, app/models/tenure/FairholdLandRent.ts, app/models/tenure/MarketPurchase.ts, app/models/tenure/MarketRent.ts, app/models/tenure/SocialRent.ts
Updated TSDoc across all modules in the `models` directory. To view docs in browser, run `npm run docs` (script is not new). 
Each time I return to this repo to work on a new feature I find that I've forgotten what a variable name means, why a property is present in a class, or similar--and then I have to re-learn my way around! Hopefully this makes that process easier for all involved. 
Feedback, eg if anything is still unclear, is very welcome.
=> docs: improve tsdoc comments for documentation clarity

app/models/Household.ts, app/models/tenure/FairholdLandRent.test.ts, app/models/tenure/FairholdLandRent.ts, app/models/tenure/MarketRent.test.ts, app/models/tenure/MarketRent.ts
- Removes `averagePrice` and `landPrice` from tenure classes `MarketRent` and `FairholdLandRent` because they were only there to be used to calculate `landToTotalRatio`, which gets calculated in Property` anyway
- Pass `landToTotalRatio` to `MarketRent` and `FairholdLandRent`
- Update tests accordingly (to fit the new params shape)
- `landToTotalRatio` was being calculated multiple times and could just be calculated once and passed where needed.
Closes #150
=> chore: calculate `landToTotalRatio` once and pass it to relevant classes

.github/workflows/deploy-migrations.yaml
The latest merge to `main` failed with the following error -
Link to CI run - https://github.com/theopensystemslab/fairhold-dashboard/actions/runs/12197345446/job/34026789936
The GH action is now configured with the variables listed here -
https://github.com/theopensystemslab/fairhold-dashboard/blob/e91c7177809ebca0cc95d18305a00b8b1079df82/prisma/schema.prisma#L5-L9
Which are configured in the repo in Settings > Secrets
=> fix(ci): Add correct Prisma secrets

.gitignore, prisma/docs/how-to-update-prisma-schema.md
- Adds description of data loss warning to backup docs
- Changes gitignore to ignore whole backups directory (not just sql files)
While the docs were super clear and I was able to carry out #166 smoothly, I knew when Daf's demo was less fresh in my mind I'd probably be very alarmed / confused by the data deletion warning, so figured it was best to clarify in the docs. 
I also backed up the db first, and found that it created a `.dump` file (rather than a `.sql` file which our gitignore expected) so just added the whole backups directory to the gitignore.
=> chore: tidy up migration docs and gitignore

jest.config.ts
I wanted to be able to use the VSCode debugger on the tests and had to update our Jest configuration slightly to get it to work.
=> feat: update jest config for debugger

app/data/buildPriceRepo.ts, prisma/migrations/20241206160747_update_build_prices_names/migration.sql, prisma/migrations/20241206161309_rename_constraint/migration.sql, prisma/migrations/20241206161734_make_build_prices_fields_required/migration.sql, prisma/schema.prisma
- Changes table and column names to Postgres convention snake_case for the `buildprices` table
- Updates code to reflect these fields as non-nullable
=> feat: Rename `build_prices` table, make fields non-nullable

app/data/gdhiRepo.test.ts, app/data/gdhiRepo.ts, prisma/migrations/20241206162843_rename_ghdi_table/migration.sql, prisma/schema.prisma
- Renames columns to snake_case
- Adds `NOT NULL` constraints
- Updates code to account for non-nullable return types
=> feat: Rename `gdhi`, add not null constraints

app/data/socialRentEarningsRepo.test.ts, app/data/socialRentEarningsRepo.ts, prisma/migrations/20241212112723_rename_social_rent_earnings/migration.sql, prisma/migrations/20241212112833_social_rent_earnings_rename_constraint/migration.sql, prisma/migrations/20241212113106_make_social_rent_earnings_fields_required/migration.sql, prisma/schema.prisma
Changes table and column names to Postgres convention snake_case for the `socialrent` table (which held social rent _earnings_ data anyway), so updated that for accuracy)
Updates code to reflect these fields as non-nullable
Basically follows #162! Closes #169
=> feat: Rename social_rent_earnings table, make fields non-nullable 

app/data/itlRepo.test.ts, app/data/itlRepo.ts, prisma/migrations/20241213132621_make_itl_lookup_field_required/migration.sql, prisma/schema.prisma
No renaming needed in this table. Makes the fields required.
=> feat: make itl_lookup fields required

prisma/migrations/20241212122143_rename_rent_table_columns/migration.sql, prisma/migrations/20241212122332_make_rent_fields_required/migration.sql, prisma/schema.prisma
Changes table and column names to Postgres convention snake_case for the `rent` table
Makes fields required
Basically follows #162!
=> feat: rename `rent` table and make fields non-nullable

prisma/migrations/20241213133842_rename_social_rent_adjustments/migration.sql, prisma/migrations/20241213134106_rename_social_rent_adjustments_constraint/migration.sql, prisma/migrations/20241213134224_make_social_rent_adjustments_field_required/migration.sql, prisma/schema.prisma
Renamed what was `soc_rent_adjustements` to `social_rent_adjustments` (for consistency, didn't abbreviate the other one).
Also makes fields required.
I believe this is the last table that needs updating so when this merges it closes #168
=> feat: rename `social_rent_adjustments` table and make fields required

app/data/hpiRepo.ts, prisma/migrations/20241206165018_update_hpi_table/migration.sql, prisma/migrations/20241206165140_lad_code_not_null/migration.sql, prisma/schema.prisma
- Renames `ladcode` to `lad_code`
- Adds `NOT NULL` constraints to columns
- Updates code to account for this constraint
=> feat: Rename `HPI` table columns, add not null constraints

prisma/migrations/20241218095140_tidy_schema_for_update/migration.sql, prisma/schema.prisma
The big data update migration failed because the shape of the incoming data didn't match the schema. This was because we had two unnecessary columns in the db, this PR removes them!
(This is a fixed version of #182)
=> feat: remove unnecessary columns from db

app/data/gdhiRepo.test.ts, app/data/gdhiRepo.ts, app/services/gdhiService.test.ts, app/services/gdhiService.ts, prisma/migrations/20241218105236_rename_gdhi_column/migration.sql, prisma/schema.prisma
While updating data I realised data naming pattern was inconsistent. I think we should stick to the pattern where there is no year suffix when the data is for the relevant year (2022) since that is what we are doing across all other tables, and only include a year suffix when the data is from a specific, older year (eg hpi_2000 because the social rent formula uses values from 2000).
Fixed (updated repo & renamed) version of #184
=> feat: rename gdhi column

app/data/gasBillRepo.test.ts, app/data/gasBillRepo.ts, prisma/migrations/20241211152923_rename_gasbills_column/migration.sql, prisma/schema.prisma
- Creates a new migration renaming some of the `gas_bills` columns
- Updates the schema accordingly
I was starting on the data update migration and realised the shape of the gas bills data will change. It seemed like this would need to happen in two steps anyway (data change and schema change) so I figured we could rename the columns first, as the supplied CSVs are already in the next shape. 
...do I need to update the tests to get everything passing even if we're just about to update the data anyway? 😅
=> feat: migration rename columns in `gas_bills` table

app/data/hpiRepo.test.ts, app/data/hpiRepo.ts, app/services/hpiService.test.ts, app/services/hpiService.ts, prisma/migrations/20241218155911_update_hpi_year/migration.sql, prisma/schema.prisma
The data update changes HPI values from 2000 to 1999, the correct input for social rent calculations.
This migration makes that change in the schema and relevant repo / service.
=> feat: update column name to hpi1999

prisma/migrations/20241218162252_remove_transaction_id_column/migration.sql, prisma/schema.prisma
This migration removes an unused column from the schema that wasn't included in the `fairhold-data` output.
=> feat: remove `transaction_identifier` column from `prices_paid`

prisma/migrations/20241218161553_rename_district_to_region/migration.sql, prisma/schema.prisma
I'm in the process of making sure that all outputs of [`fairhold-data`](https://github.com/theopensystemslab/fairhold-data) match the schema. 
This migration updates the column name `district` to `region` in the `itl_lookup` table (we use `region` in other tables).
=> feat: rename district column to region

app/models/Fairhold.ts, app/models/ForecastParameters.ts, app/models/Household.ts, app/models/Lifetime.ts, app/models/Mortgage.ts, app/models/Property.ts, app/models/constants.ts, app/models/tenure/FairholdLandPurchase.ts, app/models/tenure/FairholdLandRent.ts, app/models/tenure/MarketPurchase.ts, app/models/tenure/MarketRent.ts, app/models/tenure/SocialRent.ts
A `testHelpers.ts` file, which contains:
- helper functions that instantiate all relevant classes with simplified values
- TSdoc for each function
When writing a test for the `Lifetime` class, I realised that it needs all four tenure classes as well as the `Property` class, which contain sub-classes too. Not only was it too messy to instantiate all of that in the `Lifetime.test.ts` file, but I realised that we were creating many instances of these classes and their sub-classes across the test files, and thought it would be straightforward for all testing to have a set of helper functions that instantiate them with default values.
=> test: test helper functions

app/models/Fairhold.ts, app/models/ForecastParameters.ts, app/models/Household.ts, app/models/Lifetime.test.ts, app/models/Lifetime.ts, app/models/Mortgage.ts, app/models/Property.ts, app/models/constants.ts, app/models/tenure/FairholdLandPurchase.ts, app/models/tenure/FairholdLandRent.ts, app/models/tenure/MarketPurchase.ts, app/models/tenure/MarketRent.ts, app/models/tenure/SocialRent.ts, app/models/testHelpers.ts
In `Lifetime.ts`
- Added `depreciatedHouseResaleValue`, `fairholdLandPurchaseResaleValue` and `houseAge` properties for resale values (as these will be calculated over 'lifetimes' as well)
- Adds the above classes to the for loop to iterate through them too & push them to `lifetime` 
- Tidied the file slightly
- Made `calculateDepreciatedBuildPrice()` method in `Property` public because we'll need to call it in `Lifetime`
For story 4 in the calculator, we'll need resale values. Since they also need to be calculated over longer timespans eg lifetime, I thought it made sense to add them to the `Lifetime` class, as it had the most appropriate data structure. 
I would like to merge #151 first so that I can use the helper functions to write tests for this class (that's why this is still a …
=> feat: calculate resale values in `Lifetime` class

app/models/Property.test.ts, app/models/Property.ts, app/models/constants.ts
`constants.ts`
- Creates new types for calculating depreciation
- `componentBreakdownType` breaks each component down into the percentage of the house it makes up, how much of its original value it depreciates each year, and what percentage of yearly maintenance spend it accounts for 
- `houseBreakdownType` is an object with a component breakdown object per-component
- `HOUSE_BREAKDOWN_PERCENTAGES` is exported as a constant for use in `calculateDepreciatedBuildPrice()`
`Property.ts`
- New `calculateComponentValue()` method (separated this out for ease of testing)
- Updates `calculateDepreciatedBuildPrice()`
- Loops through each object in `HOUSE_BREAKDOWN_PERCENTAGES` and runs `calculateComponentValue()` to calculate depreciated value per-component
- Sums each value
`Property.test.ts`
- …
=> feat: update depreciation 

tsconfig.json
~~Not sure if anyone else had this lingering change locally (I believe it happened after a dependabt eslint update) but `tsconfi.json` was updated and I didn't want to lump that commit into another PR. Here's a separate PR for the minor changes!~~
Ah-ha, I think we have a conflict between what eslint wants the `tsconfig.json` to look lkike and what `dev:db` wants it to look like. Let's discuss later!
=> chore: tsconfig linting

app/models/Mortgage.test.ts, app/models/Mortgage.ts
This PR rewrites `calculateYearlyPaymentBreakdown()` and adds tests for the `Mortgage` class
While writing more class tests in another branch, I realised that the `Mortgage` method `calculateYearlyPaymentBreakdown()` was incorrectly calculating interest paid, principal paid, etc.
=> fix: Mortgage class & tests

app/components/ui/CalculatorInput.tsx, prisma/schema.prisma, tsconfig.json
Follow up to https://github.com/theopensystemslab/fairhold-dashboard/pull/229 - this should have helped us avoid this issue in the first instance.
Docs: https://www.prisma.io/docs/orm/prisma-client/special-fields-and-types/null-and-undefined
=> chore: Enable `strictUndefinedChecks` flag on Prisma

prisma/migrations/20250107110255_add_prices_paid_summary_table/migration.sql, prisma/schema.prisma
- Adds a new `PricesPaidSummary` model - this will hold pre-calculated values emulating the business logic used in `pricesPaidRepo.rs`
- The data will be populated via this script once merged to production https://github.com/theopensystemslab/fairhold-data/pull/1
- The model is implemented here - https://github.com/theopensystemslab/fairhold-dashboard/pull/241
- This needs to be a separate, follow-on, PR as it will rely on the table being already populated
=> feat: Create `prices_paid_summary` table

app/api/route.ts, app/components/ui/CalculatorInput.tsx, app/data/itlRepo.test.ts, app/data/itlRepo.ts, app/data/pricesPaidRepo.ts, app/lib/exceptions.ts, app/services/calculationService.ts
- Adds a custom `APIError` class
- Implements this where we have specific errors which require feedback for the user
- Handles these errors on the frontend and updates the form errors accordingly
- Closes https://github.com/theopensystemslab/fairhold-dashboard/issues/232
https://github.com/user-attachments/assets/4722a645-afdd-42d5-82fd-aeb03a13de14
=> feat: Gracefully handle non-English postcodes

app/models/Property.test.ts, app/models/Property.ts
I'm not 100% sure about this one so thoughts appreciated! 
While rewriting class tests, I realised the `calculateBedWeightedAveragePrice()` method and `bedWeightedAveragePrice` property were relics of an earlier calc approach. I think removing it is the right way to go. 
- The social rent calculations weight rent levels according to # of bedrooms
- Since we had a table of # of bedrooms and price weighting factors, I tried using it for the market prices too (this was back in team of 1 days and it was a relatively uninformed decision that I just wanted to try out and not necessarily keep)
- The price paid dataset distinguishes between house type, but not size (whether in m2 or bedrooms) so this was a potential way of making price estimates reflective of size
- Its application was …
=> feat: remove unnecessary bed weight calcs

app/components/ui/BackgroundAssumptions.tsx, app/components/ui/CalculatorInput.tsx
This PR adds a link as seen in Miro - the link is currently empty.
=> feat: Add background assumptions button

app/components/ui/CalculatorInput.tsx, app/components/ui/Drawer.tsx, app/components/ui/MaintenanceExplainerDrawer.tsx, app/globals.css, components/ui/sheet.tsx, package-lock.json, package.json
- Adds a `Drawer` component based on the shadcn/ui [Sheet](https://ui.shadcn.com/docs/components/sheet)
- Creates an `MaintenanceExplainerDrawer` which uses this drawer, with the required (initial) content
- This pattern can be easily expanded upon in graphs and for other form inputs as required
Hit a few issues here with colours and our mix of tailwind and CSS variables - we should probably stick to one (Tailwind?) but we can discuss this tomorrow and fix forward.
https://github.com/user-attachments/assets/76230a05-6f9f-4e9d-b0f4-67c1b47ede13
=> feat: Initial drawer setup

app/components/ui/CalculatorInput.tsx, app/models/Mortgage.ts, app/models/constants.ts
NB: we are using 0 for newbuild age now
Q: see comment in line 330 (should we hook up the mortgage variable explainers to the actual constants so we don't have to maintain them in two places?)
=> nit: fix placeholder copy in form

app/components/ui/CalculatorInput.tsx, app/models/Household.ts, app/models/Lifetime.test.ts, app/models/Lifetime.ts, app/models/Property.test.ts, app/models/Property.ts, app/models/constants.ts
- Adds 'none' option to `MAINTENANCE_LEVELS` constant
- Adds new properties to the `Lifetime` class to calculate how `maintenanceCost` changes over time and thus `depreicatedHouseResaleValue` does (for all maintenance levels: none, low, medium and high
- Creates tests for the new calcs
- I think my last PR managed to remove a default value for the maintenance selector, so fixes that
So that we can graph them
Does this make the `Lifetime` class a bit too messy? Should we instead just use `maintenanceCost` and `depreciatedHouseResaleValue` properties that store objects, instead of multiple properties (eg `maintenanceCostLow`, `maintenanceCostMedium` and `maintenanceCostHigh`? 
Closes #240 and #239
=> feat: calculate house depreciation for all maintenance levels

app/schemas/calculationSchema.ts, app/schemas/formSchema.ts
It changes the validation schema to allow for a value equal to 0 in the House Age field. This is because now a new house has year equal to 0 and not equal to 1.
=> chore: allow House age to be 0

app/components/ui/CalculatorInput.tsx
I merged a silly mistake that running `build` didn't catch!
This PR changes the maintenance selector _values_ to be strings ("low", "medium" and "high") now instead of numbers.
=> fix: maintenance selector button values

app/components/graphs/ResaleValueWrapper.tsx, app/models/Lifetime.test.ts, app/models/Lifetime.ts
Makes previous properties into objects to tidy up the `Lifetime` class
Having multiple similar properties seemed verbose (eg `maintenanceCostLow`, `maintenanceCostMedium`, `maintenanceCostHigh`) but also placing them in objects with `MaintenanceType` type keys will make them easier to access elsewhere. This came up when working on graph 2, which is why I'm doing it now!
=> feat: new `maintenanceCost` and `depreciatedHouseResaleValue` objects in `Lifetime`

app/components/Dashboard/Cards/CostOverTime.tsx, app/components/graphs/CostOverTimeStackedBarChart.tsx, app/components/graphs/CostOverTimeWrapper.tsx, app/components/graphs/TenureComparisonBarChart.tsx, app/components/ui/CalculatorInput.tsx, app/components/ui/Dashboard.tsx, app/globals.css, app/models/Lifetime.ts, app/models/constants.ts
- Calculates social rent over lifetime (I closed #292 because I needed this functionality in this PR)
- Components for CostOverTime chart, wrapper and card 
- Adds CostOverTime graph to the dashboard
- Updated colours for house values too
886cdee is a cherry-pick of #291 which I needed to fix an error. Unsure what the best git practice should have been here!
=> feat: costs over lifetime graphs

app/components/Dashboard/Cards/CostOverTime.tsx, app/components/Dashboard/Cards/ResaleValue.tsx, app/components/graphs/CostOverTimeWrapper.tsx, app/components/graphs/ResaleValueWrapper.tsx, app/components/ui/TenureSelector.tsx, app/globals.css
- Renamed `{tenure}-maintenance-color` to `{tenure}-detail-color` since we are using the colours not just for maintenance but also for the background of the TenureSelector component, as per Alastair's designs
- Rounded the corners too 😮 again per design
Design:
Current UI:
Would appreciate some feedback on colours, concerned about contrast!
=> feat: add tenure selector colours and update shape

app/models/Household.ts, app/models/Lifetime.ts
When working on social value, I found we needed to access the kwh demand figure from `Household`, so this PR refactors `Household` to store those values in a new `gasDemand` object property and makes its methods more concise too.
=> feat: add gas object to Household

app/components/Dashboard/Cards/WhatDifference.tsx, app/components/ui/Dashboard.tsx, app/models/Household.ts, app/models/SocialValue.test.ts, app/models/SocialValue.ts, app/models/constants.ts
- Creates a new `SocialValue` class within `Household` (and associated tests)
- Renders `SocialValue` figures in the `WhatDifference` card
=> feat: social value calculations

app/components/Dashboard/Cards/WhatDifference.tsx
Round carbon and jobs to 1 decimal place & finished replacing accessed data with variables. (Missed two out of last PR!)
=> nit: tidy decimal places and var storage

app/components/Dashboard/Cards/WhatDifference.tsx, app/models/SocialValue.ts, app/models/constants.ts
- Update / fixes the way we individualise the cost of poor housing (from BRE report)
- Adds broader cost to society (in addition to existing cost to NHS)
- Makes the figures per-household, not per-head (I figured we could just make this static, we also have the option of doing this by # of bedrooms instead of assuming an average household size of 2.4)
Draft until getting Alastair's feedback on the change; closes #303
=> feat: render housing quality savings NHS and society

app/components/graphs/CostOverTimeStackedBarChart.tsx, app/components/graphs/CostOverTimeWrapper.tsx, app/components/graphs/ResaleValueLineChart.tsx, app/components/graphs/TenureComparisonBarChart.tsx, app/components/graphs/UpfrontComparisonBarChart.tsx, app/components/ui/TenureSelector.tsx, app/globals.css, app/models/Household.ts, app/models/Lifetime.test.ts, app/models/Lifetime.ts, app/models/Mortgage.ts, app/models/SocialValue.ts, app/models/testHelpers.ts
- Reorganises the `Lifetime` class to include `LifetimeMortgageBreakdown` type, which breaks yearly mortgage payments down into equity accumulated and interest paid
- new `getMortgageBreakdown()` method pulls in mortgage payment data from `Mortgage` class
- Updates the bar chart and wrapper to access the new data structure
- Fixed mortgage related colours (from `land` and `house` to `equity` and `interest`(other tenure colour fixes will come in another PR)
- We needed a new colour for Fairhold Land Rent land rent
We want to be able to show the split of mortgage payments by equity and interest, not land and house.
=> feat: split mortgage payments into principal repayment (equity) and interest

app/api/route.test.ts, app/api/route.ts, app/models/calculateFairhold.ts
It renames the `testClasses.ts` file into `calculateFairhold.ts`.
I think the name `testClasses.ts` is misleading because no test is involved. The file contains the function calculateFairhold, so maybe we should change its name?
I was thinking actually a follow up PR should be developing the unit testing for it, i.e. `calculateFairhold.test.ts` because it is currently missing. OThinking of a file named `testClasses.test.ts` will become even more confusing to me
=> chore: rename testClasse file

app/models/SocialValue.ts, app/models/constants.ts
- Adds constants for kg of carbon equivalent per m2 of construction method
- Uses those constants to calculate embodied carbon by house size
Our previous value was hard-coded and static
Closes #325
=> feat: calculate embodied carbon saved by area

app/components/Dashboard/Cards/WhatDifference.tsx, app/models/Lifetime.test.ts, app/models/Lifetime.ts
- Adds another object to `Lifetime` to store inflating savings to NHS and society
- Both iterative and cumulative versions, so we get total lifetime save
- Shows the cumulative values in the WhatDifference` card
Following convo with Alastair, decided to show health savings over a lifetime rather than just yearly
=> feat: calculate NHS / social save over lifetime (instead of annual)

app/components/Dashboard/Cards/HowMuchFHCost.tsx, app/components/Dashboard/Cards/HowMuchPerMonth.tsx, app/components/graphs/CostOverTimeStackedBarChart.tsx, app/components/graphs/CostOverTimeWrapper.tsx, app/components/graphs/HowMuchFHCostBarChart.tsx, app/components/graphs/HowMuchFHCostWrapper.tsx, app/components/graphs/HowMuchPerMonthBarChart.tsx, app/components/graphs/HowMuchPerMonthWrapper.tsx, app/components/graphs/ResaleValueLineChart.tsx
- Renames graphs and their wrappers so that they match their content card names in `Dashboard/`
- Removes tooltip from graph 2 because I thought it was redundant (❓ unsure about this one, what do people think?? The old tooltip label just showed what was already in the bar)
- Changes tooltip in graph 1 to match styling in 3 and 4 (and to show 'Total' instead of redundant information)
Before: 
After: 
- Makes axes naming and styling consistent in graphs 3 and 4
Closes #330
=> chore: tidy graphs

app/components/graphs/CostOverTimeStackedBarChart.tsx, app/components/graphs/HowMuchFHCostBarChart.tsx, app/components/graphs/HowMuchPerMonthBarChart.tsx, app/components/graphs/ResaleValueLineChart.tsx, app/components/ui/StyledChartContainer.tsx
Adds `className` to instances of `ChartContainer` to remove the previous background colour.
Follow up question: should we change the tooltip to only show when the visible bar is hovered over?
Closes #326
=> feat: remove bar graph hover background

app/data/pricesPaidRepo.ts, prisma/migrations/20250214104412_create_filtered_price_paid_summary/migration.sql, prisma/schema.prisma, scripts/export_price_paid.sql, scripts/export_prices.sh
What does this PR do?
- Filters prices paid data by area (eg SE) by first and last quartiles
Why?
Following [Gabry's suggestion](https://opensystemslab.slack.com/archives/C01RF806126/p1739524249696609?thread_ts=1739465942.321799&cid=C01RF806126), trying to create slightly more realistic data.
While sometimes the difference between freehold and private rent is even greater than in the other two methods, ultimately I think this method leads to the closest figures. 
This branch uses `oz/weight-purchase-price` as a base, so the property weightings and rental data by number of bedrooms are also inputs.
=> feat: create filtered prices paid summary table (filter out outliers)

app/data/pricesPaidRepo.test.ts, app/data/pricesPaidRepo.ts, app/data/rentRepo.test.ts, app/data/rentRepo.ts, prisma/migrations/20250214104412_create_filtered_price_paid_summary/migration.sql, prisma/migrations/20250228120125_make_bedrooms_required/migration.sql, prisma/schema.prisma, scripts/export_price_paid.sql, scripts/export_prices.sh
This re-opens #329 since I had some unexpected test failures and had to revert the merge. 
Original PR description below!
___
What does this PR do?
- Filters prices paid data by area (eg SE) by first and last quartiles
Why?
Following [Gabry's suggestion](https://opensystemslab.slack.com/archives/C01RF806126/p1739524249696609?thread_ts=1739465942.321799&cid=C01RF806126), trying to create slightly more realistic data.
While sometimes the difference between freehold and private rent is even greater than in the other two methods, ultimately I think this method leads to the closest figures. 
This branch uses `oz/weight-purchase-price` as a base, so the property weightings and rental data by number of bedrooms are also inputs.
=> feat: remove price paid dataset outliers

app/components/graphs/HowMuchPerMonthBarChart.tsx, app/models/Household.ts, app/models/SocialValue.test.ts, app/models/constants.ts
Adds the 35% of household income line
following designs
=> feat: add affordability threshold to monthly cost graph

app/components/graphs/HowMuchFHCostBarChart.tsx
This isn't perfect but I'm hoping it'll do for now.
Trying to get from current deployed version:
to design:
this is how my PR will render the label:
=> wip: formatValueWithLabel

app/components/Dashboard/Cards/CostOverTime.tsx, app/components/Dashboard/Cards/HowMuchFHCost.tsx, app/components/Dashboard/Cards/HowMuchPerMonth.tsx, app/components/Dashboard/Cards/ResaleValue.tsx, app/components/Dashboard/Cards/WhatDifference.tsx, app/components/Dashboard/Help/CostOverTime.md, app/components/Dashboard/Help/HowMuchFHCost.md, app/components/Dashboard/Help/HowMuchPerMonth.md, app/components/Dashboard/Help/ResaleValue.md, app/components/Dashboard/Help/WhatDifference.md, app/components/ui/Drawer.tsx, app/models/Lifetime.ts, app/models/constants.ts, custom.d.ts, next.config.mjs, package-lock.json, package.json
- Installs `react-markdown`
- New directory `Dashboard/Help/` that stores the drawer content in markdown files, named identically to the cards themselves
- Updates the cards to use the markdown content
- Some of the cards use string processing and `.replace()` in order to not hard-code variables 
- I also had to move a tiny bit of math out of a constant and into the `Lifetime` class
- Maintaining separate markdown files with the side drawer content in is easier than dealing with HTML tags etc., thanks to Daf for [pattern suggestion](https://opensystemslab.slack.com/archives/C01RF806126/p1738062818961619?thread_ts=1738062572.110359&cid=C01RF806126)
❓ Is there a tidier way of going about rendering Markdown in the drawer?
❓ Most of this PR is Markdown (which is why there are so many lines), …
=> feat: side drawer 'Find out more...' content

app/components/Dashboard/Cards/WhatDifference.tsx
In cases where a Fairhold home would be more expensive than market (eg newbuild in an area with negative land values / where the market price of a home is less than construction cost)
Previous:
=> feat: bottom out money saved at 0

app/components/graphs/CostOverTimeWrapper.tsx
We were previously scaling the y axis here to the nearest 100k, which looked a bit funny if house prices / spend were very low:
Have used an `if` ternary to scale the y axis to 50k if the max value is less than that:
=> feat: scale y axis according to max value

app/components/graphs/HowMuchPerMonthBarChart.tsx, app/data/gdhiRepo.test.ts, app/data/gdhiRepo.ts, app/models/Household.ts, app/models/SocialValue.test.ts, app/models/calculateFairhold.ts, app/models/constants.ts, app/models/testHelpers.ts, app/services/calculationService.test.ts, app/services/calculationService.ts, app/services/gdhiService.test.ts, app/services/gdhiService.ts, prisma/migrations/20250305100045_use_median_gdhi_data/migration.sql, prisma/schema.prisma
- Migration to drop all previous GDHI data, replace `itl3` column with `itl1` and insert new median GDHI data
- Update GDHI repo and service accordingly 
- Update `Household` class (eg we no longer need per-head income, `HEADS_PER_HOUSEHOLD` constant and a household income property; we just retrieve the one household income figure and save to `Household.incomeYearly` 
Our previous GDHI data was using average income per-head and multiplying this by the average household size. This led to higher and less accurate household income figures. 
- Update the help text on how this was calculated (see PR #323)
- Update sources (`gdhi` script in [fairhold-data](https://github.com/theopensystemslab/fairhold-data) becomes redundant; source should also be updated to …
=> feat: use median GDHI data instead of average

app/components/Dashboard/Cards/CostOverTime.tsx, app/components/Dashboard/Cards/HowMuchPerMonth.tsx, app/components/Dashboard/Cards/ResaleValue.tsx, app/components/Dashboard/Cards/types.ts, app/components/Dashboard/Help/CostOverTime.md, app/components/Dashboard/Help/HowMuchFHCost.md, app/components/Dashboard/Help/HowMuchPerMonth.md, app/components/Dashboard/Help/ResaleValue.md, app/components/Dashboard/Help/WhatDifference.md, package-lock.json, package.json
- Installs relevant dependencies (`remark` for string processing and `unis-util-visit` which is used to iterate through the 'nodes' of markdown content and replace values where needed)
- In the relevant cards, Use `remark` to replace previous usage of `.replace` method
- New file `Dashboard/Cards/types.ts` with the `TextNode` type (to resolve type issue)
- Doing string processing directly on the markdown files was vulnerable to injection attacks
=> feat: safe string replace when rendering markdown

app/components/graphs/CostOverTimeStackedBarChart.tsx
In cost over time graph:
other years show as before:
Closes #386
=> feat: add deposit to y1 tooltip

app/models/constants.ts
When working on the documentation for the social value section of the calculator (see [wiki](https://github.com/theopensystemslab/fairhold-dashboard/wiki)), l wasn't able to replicate some of the constants and so am updating (with docs this time..!). 
I'd appreciate another pair of eyes on how both of these figures were calculated.
=> fix: social value constants

app/components/graphs/HowMuchPerMonthBarChart.tsx
Old version:
New (with axes and splitting the 35% threshold label over two lines):
Recharts can't render JSX so we can't use `\n` or `<br>` to create a line break. I'm not sure if my solution is overly complex--couldn't figure anything else out but I have to say I don't like it very much!
=> feat: add axes and split line 35% threshold label in monthly cost graph

app/components/Dashboard/Cards/CostOverTime.tsx, app/components/Dashboard/Cards/HowMuchFHCost.tsx, app/components/Dashboard/Cards/HowMuchPerMonth.tsx, app/components/Dashboard/Cards/ResaleValue.tsx, app/components/graphs/CostOverTimeStackedBarChart.tsx, app/components/graphs/CostOverTimeStackedBarChartMobile.tsx, app/components/graphs/CostOverTimeWrapper.tsx, app/components/graphs/HowMuchFHCostBarChart.tsx, app/components/graphs/HowMuchFHCostWrapper.tsx, app/components/graphs/HowMuchPerMonthBarChart.tsx, app/components/graphs/HowMuchPerMonthWrapper.tsx, app/components/graphs/ResaleValueLineChart.tsx, app/components/graphs/ResaleValueWrapper.tsx, app/components/ui/GraphCard.tsx, app/hooks/UseScreenSize.tsx
- Responsive styling in the graphs: just looking at layout for the moment, not addressing all of Alastair's new changes in [Figma](https://www.figma.com/design/SThTPsRJbUzhgPJIgjIXdo/Fairhold-Calculator?node-id=0-1&t=Ow50PrRJhYO13L7A-1)
- New CostOverTimeStackedBarChartMobile component (this is the only one that needs to rotate on mobile), conditional logic / new `UseScreenSize` hook will select which one to render
-  `GraphCard` component now has responsive titles / subtitles
Closes #360
=> feat: responsive graphs dashboard

app/components/Dashboard/Cards/HowMuchFHCost.tsx, app/components/graphs/HowMuchFHCostBarChart.tsx
- Adds totals on the top left of each bar (uses the parent element to position, thanks Daf for the suggestion!)
- Adds Fairhold as % of market in subtitle (with coloured highlight)
- Updates tooltip to show value breakdown based on what part of bar is being hovered over
- Re-styles tooltip
- Removes values from chart label
- Fixes mobile width
- Adds colours to bar labels (on x axis)
Mobile:
Desktop:
Tooltip:
Closes #413
=> feat: restyle up-front cost graph

app/components/ui/BackgroundAssumptions.tsx, tailwind.config.ts
A tiny PR to fix different colours, making `a` and `span` elements use `text-inaccessible-rgb` in the Tailwind config file (great shout Daf!). They still look kind of different to me 😅 but browser dev tools tells me that they are both ABA4A4. 
`BackgroundAssumptions` still needed the colour to be overwritten and I specified `decoration` there too.
Previous:
Now:
Closes #416
=> fix: more info button colours

app/components/Dashboard/Cards/WhatDifference.tsx, app/models/SocialValue.test.ts, app/models/SocialValue.ts, app/models/constants.ts
Restyles the social value card (`WhatDifference`) and makes some minor updates to the `SocialValue` class since we decided to show benefits over `lifetime` length and not the somewhat arbitrary 10 year perios. 
In line 56, the effects of `flex-col` and `flex-row` seem to be reversed. Am I being stupid? I removed styling from parent and grandparent etc. elements to try to isolate the issue and wasn't able to, so just kept the classes as is to achieve desired look. 
___
I'd say the bulk of the restyling is done, this is what desktop looks like:
And responsive sizes etc are working on mobile (scrolling / snap is a separate issue so I would like to keep that in a separate PR):
Design for reference:
=> feat: restructure and restyle social value

app/components/Dashboard/Cards/CostOverTime.tsx, app/components/Dashboard/Cards/HowMuchFHCost.tsx, app/components/Dashboard/Cards/HowMuchPerMonth.tsx, app/components/Dashboard/Cards/ResaleValue.tsx, app/components/Dashboard/Cards/WhatDifference.tsx, app/components/Dashboard/Cards/WhatWouldYouChoose.tsx, app/components/ui/Dashboard.tsx, app/components/ui/GraphCard.tsx, app/globals.css
Enables snap _and_ scroll on mobile (when cards are too long for screen height)
Should close #392 
Can anyone identify the bug (described in the issue above ^) persisting? Not seeing it in my tests!
=> feat: snap scroll

app/components/ui/BackgroundAssumptions.tsx, tailwind.config.ts
Reverts theopensystemslab/fairhold-dashboard#418
I think this PR made the dropdown menu the wrong colour:
I also thought this would be a quick fix and I've spent about an hour on it and can't crack it, so opting for revert
=> Revert "fix: more info button colours"

app/components/ui/Carousel.tsx
Following mobile designs.
Before:
After:
=> feat: hide carousel dots on mobile

app/components/Dashboard/Cards/CostOverTime.tsx, app/components/graphs/CostOverTimeStackedBarChart.tsx, app/components/graphs/CostOverTimeStackedBarChartMobile.tsx
- Restyles tooltip (changes colour, shape, and labels: y1 equity to "Deposit", other equity to "Repayment)
- Updates tenure selector copy
All to match new designs
Current:
- What should we do about the contrast of the darker colours (thinking of Freehold specifically)
- Can we live without the little circles in the tooltip Figma? See below:
Closes #406
=> feat: restyle CostOverTime graph

app/components/Dashboard/Cards/HowMuchPerMonth.tsx, app/components/graphs/HowMuchPerMonthBarChart.tsx, app/components/graphs/HowMuchPerMonthWrapper.tsx
- Moves labels on top of bars
- Colour codes bar labels and x-axis labels too
- Makes affordability threshold line and text black and solid
- Updates copy
- Adds 35% explainer to help text button
Desktop
Mobile
Closes #405
=> feat: restyle monthly costs graph

app/components/ui/CalculatorInput.tsx, app/components/ui/InputDropdown.tsx, app/components/ui/InputField.tsx, app/globals.css
Makes the error colour brighter to follow designs, and adds conditional error styling based on `fieldState`. 
Before:
After:
Closes #410
=> feat: restyle form errors

app/components/Dashboard/Cards/CostOverTime.tsx, app/components/Dashboard/Cards/ResaleValue.tsx, app/components/Dashboard/Cards/types.ts, app/components/graphs/CostOverTimeStackedBarChart.tsx, app/components/graphs/CostOverTimeStackedBarChartMobile.tsx, app/components/ui/TenureSelector.tsx, app/components/ui/TenureSelectorMobile.tsx
- Creates a new `TenureSelectorMobile` component to render for lifetime costs graph on mobile. 
- Creates a new `TENURE_COLORS_LIGHT` object in `CostOverTime.tsx` to store the second colour and renames what was `TENURE_COLORS` to `TENURE_COLORS_DARK`. 
- Refactors `TenureSelector` to select colours using the same pattern and objects. 
Closes #403 
___
I made a version which looked like this which I thought worked well (more contrast on mobile):
But ultimately styled it like this, as per designs:
=> feat: mobile tenure selector

app/components/Dashboard/Cards/CostOverTime.tsx, app/components/Dashboard/Cards/HowMuchPerMonth.tsx, app/components/Dashboard/Cards/ResaleValue.tsx, app/components/ui/Drawer.tsx, app/globals.css
- Makes full stops in subtitles consistent
- [Mobile] Make help text icon size (and text justification) uniform
- Adjust colours to improve `CostOverTime` tooltip contrast
Help text before:
Help text after:
Tooltip before:
Tooltip after:
Closes #452
=> feat: tidy styles

app/components/Dashboard/Cards/HowMuchFHCost.tsx, app/components/graphs/HowMuchFHCostBarChart.tsx, app/components/graphs/HowMuchFHCostNotViableBarChart.tsx, app/components/graphs/HowMuchFHCostWrapper.tsx, app/globals.css
Current:
Mobile:
If the build cost line happens to intersect with the labels, the labels will render on top with a background too:
Closes #407
=> feat: implement 'not viable' view

app/components/ui/TenureSelector.tsx
Fixes a styling bug. 
The issue was with the fact I was trying to dynamically create Tailwind classes using template literals, which wouldn't work at buildtime. 
Before:
This PR:
Designs:
Closes #467
=> fix: match tenure colours to selected TenureSelector button

app/models/Lifetime.ts, app/models/Property.ts
Fixes bug where the user selected maintenance level was being used to calculate `depreciatedBuildPrice` (instead of our default `low`). User selected maintenance level should only be used in the resale value highlight graph. 
Closes #468
=> fix: use default low maintenance level in calculateFairhold

app/components/Dashboard/Cards/ResaleValue.tsx, app/components/graphs/ResaleValueLineChart.tsx
- Updates subtitle
- Adds `LabelList` for line labels at the right side of graph
- Restyles tooltip as per design
- Uses tooltip pattern from `HowMuchFHCostBarChart` to only show when selected maintenance level line is hovered over
Current:
Before:
=> style: restyle resale value card

app/components/ui/CalculatorInput.tsx, app/components/ui/InputField.tsx
This is a fix for the bug that Gabry found--but it looks like it's only happening on local / development environments. On the deployed Vercel version it doesn't seem to be a problem, I checked other PR previews too. 
Unsure if this fix is still needed? It has addressed the bug on my local branches however. 
What I've done is give the bedrooms input field a default blank value so that it's always a controlled input. I made the `InputFieldProps` type an extension of `React.InputHTMLAttributes<HTMLInputElement>` so that it would take `value` as a property. 
Closes #461
=> fix: always give bedrooms input a controlled value

app/survey/components/CustomSankey.tsx, app/survey/components/SurveyGraphCard.tsx, app/survey/components/graphs/AffordFairhold.tsx, app/survey/components/graphs/Age.tsx, app/survey/components/graphs/AnyMeansTenureChoice.tsx, app/survey/components/graphs/Country.tsx, app/survey/components/graphs/CurrentMeansTenureChoice.tsx, app/survey/components/graphs/HouseType.tsx, app/survey/components/graphs/HousingOutcomes.tsx, app/survey/components/graphs/IdealHouseType.tsx, app/survey/components/graphs/IdealLiveWith.tsx, app/survey/components/graphs/LiveWith.tsx, app/survey/components/graphs/Postcode.tsx, app/survey/components/graphs/SupportDevelopment.tsx, app/survey/components/graphs/SupportDevelopmentFactors.tsx, app/survey/components/graphs/SupportNewFairhold.tsx, app/survey/page.tsx, app/survey/types.tsx, app/survey/utils.tsx
- Creates a `CustomSankey` component
- Creates graphs for the "Housing preferences" section of the page
- Refactors and updates utility functions in `aggregateResults()` to correctly count Sankey data
- Makes prop passing to graphs consistent
=> feat: graphs for 'Housing preferences' section

app/survey/components/CustomSankey.tsx, app/survey/components/SurveyGraphCard.tsx, app/survey/components/graphs/AffordFairhold.tsx, app/survey/components/graphs/Age.tsx, app/survey/components/graphs/AnyMeansTenureChoice.tsx, app/survey/components/graphs/Country.tsx, app/survey/components/graphs/CurrentMeansTenureChoice.tsx, app/survey/components/graphs/HouseType.tsx, app/survey/components/graphs/HousingOutcomes.tsx, app/survey/components/graphs/IdealHouseType.tsx, app/survey/components/graphs/IdealLiveWith.tsx, app/survey/components/graphs/LiveWith.tsx, app/survey/components/graphs/Postcode.tsx, app/survey/components/graphs/SupportDevelopment.tsx, app/survey/components/graphs/SupportDevelopmentFactors.tsx, app/survey/components/graphs/SupportNewFairhold.tsx, app/survey/page.tsx, app/survey/types.tsx, app/survey/utils.tsx, jest.config.ts
Creates two sub-types for results: `BarOrPieResults` and `SankeyResults` since the data structures needed were quite different. Now the `SurveyResults` type holds `numberResponses`, `barOrPie` and `sankey`. I split them into two keys because it was becoming quite convoluted to distinguish between which properties should have the bar/pie formatting and which the sankey formatting. It was also getting needlessly complex to distinguish between which properties to overwrite or drop in the case of sankeys, where two properties from `RawResults` get aggregated into one. 
The original `aggregateResults()` function in #485 only formats for a bar or pie chart type, and we needed to format for sankeys too.
=> feat: format sankey data too

app/components/ui/Dashboard.tsx, app/globals.css
=> chore: remove extra scrollbar

app/survey/components/graphs/AffordFairhold.tsx, app/survey/components/graphs/Age.tsx, app/survey/components/graphs/AnyMeansTenureChoice.tsx, app/survey/components/graphs/Country.tsx, app/survey/components/graphs/CurrentMeansTenureChoice.tsx, app/survey/components/graphs/HousingOutcomes.tsx, app/survey/components/graphs/IdealHouseType.tsx, app/survey/components/graphs/IdealLiveWith.tsx, app/survey/components/graphs/SupportDevelopment.tsx, app/survey/components/graphs/SupportDevelopmentFactors.tsx, app/survey/components/graphs/SupportNewFairhold.tsx, app/survey/components/graphs/WhyFairhold.tsx, app/survey/components/graphs/WhyNotFairhold.tsx, app/survey/context.tsx, app/survey/page.tsx
Instead prop-drilling and passing survey results to all child components as props, this refactor uses React context to share directly with the components. 
Closes #493
=> refactor: use context for surveys

app/components/graphs/HowMuchFHCostBarChart.tsx, app/components/graphs/HowMuchFHCostNotViableBarChart.tsx, app/components/graphs/HowMuchPerMonthBarChart.tsx, app/components/graphs/ResaleValueLineChart.tsx, app/components/graphs/shared.tsx, app/components/graphs/types.tsx
- Renames `types.ts` to `shared.ts` (not strictly types anymore, nor utils)
- Creates a shared `CustomTick` component for coloured tenure labels and `BarLabelListTopLeft` for labels coloured by tenure that sit on the top left of bars
- We do use custom LabelList components elsewhere, but their styling / formatting is different and it didn't make sense to combine
- Continuing the refactor started in #510 but I think my brain needed to do it incrementally! 
Closes #526
=> refactor: share custom components where possible

app/components/graphs/HowMuchFHCostBarChart.tsx, app/components/graphs/HowMuchFHCostNotViableBarChart.tsx, app/components/graphs/HowMuchPerMonthBarChart.tsx, app/components/graphs/ResaleValueLineChart.tsx, app/components/graphs/shared.tsx, app/components/graphs/types.tsx
My `CustomLabelList` refactor from before (#510) messed up the labels in the 'not viable' view, which I only just noticed today. 
This PR fixes that label, refactors another set of complex inline props that I neglected, and removes the unnecessary tooltip from the 'not viable' view (not in designs!). 
The custom tooltips could do with yet another refactor given repetition but hoping to fix-forward. 
Before fix:
After fix:
=> chore: 'not viable' view refactor

app/globals.css, app/survey/components/SurveyGraphCard.tsx, app/survey/components/TenureSelector.tsx, app/survey/components/graphs/AnyMeansTenureChoice.tsx, app/survey/components/graphs/HousingOutcomes.tsx, app/survey/constants.tsx, app/survey/types.tsx, app/survey/utils.tsx, package-lock.json, package.json
- New `TenureSelector.tsx` component in `survey/`
- Updates in aggregation (in `utils.tsx` and `types.tsx`) because previous `housingOutcomes` data shape / graph showed them aggregated across tenures, rather than split by current tenure
- Updates `SurveyGraphCard` to take optional `action` prop (where `TenureSelector` can be passed)
- Styles (adds subtitle, removes x and y axis lines etc.)
- Limits results to 5
As per designs!
Before:
After:
=> feat: display housing outcomes by current tenure

app/globals.css, app/survey/components/SurveyGraphCard.tsx, app/survey/components/TenureSelector.tsx, app/survey/components/graphs/AnyMeansTenureChoice.tsx, app/survey/components/graphs/HousingOutcomes.tsx, app/survey/components/graphs/SupportDevelopmentFactors.tsx, app/survey/components/graphs/WhyFairhold.tsx, app/survey/components/graphs/WhyNotFairhold.tsx, app/survey/constants.tsx, app/survey/types.tsx, app/survey/utils.tsx, package-lock.json, package.json
Updates styles for bar graphs that do _not_ need the data shape to change. 
Will do the more elaborate changes in further PRs (eg housing outcomes with ability to select tenure)
=> style: restyle bar graphs

app/survey/constants.tsx, app/survey/utils.tsx
- Adds `ageGroup` custom order to `constants.ts`
- Creates custom ordering functionality in `utils.ts`, sort descending if no custom order found
- The new designs have a mixture of custom orders for bar / pie graphs, and descending--need to be able to handle both.
=> feat: order results descending or custom

app/globals.css, app/survey/components/SurveyGraphCard.tsx, app/survey/components/SurveyTenureSelector.tsx, app/survey/components/graphs/AnyMeansTenureChoice.tsx, app/survey/components/graphs/HousingOutcomes.tsx, app/survey/components/graphs/SupportDevelopmentFactors.tsx, app/survey/components/graphs/WhyFairhold.tsx, app/survey/components/graphs/WhyNotFairhold.tsx, app/survey/constants.tsx, app/survey/page.tsx, app/survey/types.tsx, app/survey/utils.tsx
I'm not sure how but when merging #545, #544, #543, #542 and #541 last week somehow a bunch of changes didn't make it in.  Adding the styles back in here! 
Changes to:
**Housing outcomes**
- New `SurveyTenureSelector` component
- Passes optional `action` to `SurveyGraphCard` for `SurveyTenureSelector`
- Updates type and `handleHousingOutcomes` to aggregate results by current tenure
- Coloured styling
**Why Fairhold / Why Not Fairhold**
- Axes and colour styling
- `getTopFive` util function to show top five results each 
**Ranked tenure choice**
- Bar not sankey
- Aggregation through weight 
- Custom colours and label 
**Support development factors**
- Axes, colour & height styling
=> style: missing survey results graph styles

app/page.tsx, app/results/page.tsx, components/custom/ui/CalculatorInput.tsx, schemas/formSchema.ts
This is a new version of #508 (closed because of messy rebase and to improve separation of concerns) _and_ #580 (because rebasing got too messy). 
Creates a new route at /results for survey dashboard
Moves conditional rendering to /results/page.tsx (it probably shouldn't have been in CalculatorInput.tsx anyway!)
We decided to create a new route for results so that if people hit 'back' to change any of their form inputs, they wouldn't get redirected to their previous non-Fairhold page / referrer.
I was thinking about [Daf's comment here](https://github.com/theopensystemslab/fairhold-dashboard/pull/508#discussion_r2177813846) and wondered if maybe we would want to route people to `/results?housePostcode=abc123`--eg I want to share with my flatmates / partner what our home would cost if it …
=> feat: new route for calculator results v3

components/custom/survey/SurveyTenureSelector.tsx
Following on from #597, forgot there was another dropdown in the survey results that would also need focus! While I was here added a thin border for visibility. 
Before:
After:
=> style: SurveyTenureSelector dropdown focus

components/custom/survey/graphs/AnyMeansTenureChoice.tsx, components/custom/survey/graphs/HousingOutcomes.tsx, components/custom/survey/graphs/SupportDevelopmentFactors.tsx, components/custom/survey/graphs/WhyFairhold.tsx, components/custom/survey/graphs/WhyNotFairhold.tsx, lib/survey/constants.tsx, lib/survey/utils.tsx
- Creates new `shortenStrings()` function to shorten labels
- User input strings (eg if they selected 'Other') will be returned as `Other` by `shortenStrings()` (eg in case of typos, malicious entries, and because it would just be messy). New `aggregateOther()` function will combine different instances of answer `Other` into one
- Creates new objects for mapping full to shortened label, nesting them within `LABEL_MAP`
- Shortens labels before sorting and slicing
As discussed with Alastair, survey answers can be too long for concise graphs. 
Before:
Afte
r:
=> feat: shortenStrings for bar labels

app/globals.css, app/survey/page.tsx, components/custom/survey/CustomSankey.tsx, components/custom/survey/graphs/CurrentMeansTenureChoice.tsx, components/custom/survey/graphs/IdealHouseType.tsx, components/custom/survey/graphs/IdealLiveWith.tsx, lib/survey/constants.tsx, lib/survey/utils.tsx
- Adds colours for all tenure options to `globals.css`
- Enable color props in `CustomSankey` nodes and links
- Add left and right labels to `SankeyProps`
- Adjusts data aggregation for `currentMeansTenureChoice`
- Accesses optional properties `rentalModel` and `ownershipModel` for granular tenure options (decided in roadmap that we wanted to show eg freehold or leasehold, not just ownership)
- Adds suffixes here for current and ideal (`_0` and `_1` respectively, to avoid circular loop in case of Freehold -> Freehold)
- New `applyNodeColors` util function for mapping tenures to colors
- Replace suffixes in `CurrentMeansTenureChoice` labels
- Some minor style adjustments & tidying up
As per designs!
Now we have:
Closes #555 and #556
=> style: add colours and labels to sankeys

lib/survey/constants.tsx
Tiny PR just to shorten the labels on the support development doughnut and ensure that order is correct.
=> chore: update support development labels

components/custom/survey/graphs/AnyMeansTenureChoice.tsx, components/custom/survey/graphs/SupportDevelopmentFactors.tsx, components/custom/survey/graphs/WhyFairhold.tsx, components/custom/survey/graphs/WhyNotFairhold.tsx, lib/survey/utils.tsx
This makes the spacing between bars consistent by
1. adjusting the height of `ResponsiveContainer` (defining a `barGap` leads to auto `barSIze` and vice versa, so that wasn't an option since we wanted sizes and gaps to be consistent)
2. ensuring that all tenures have the same number of bars in `housingOutcomes` by padding out the number of answers listed and sorting / slicing (in new helper function `padAndSortHousingOutcomes()`)
Before:
After:
=> style: make bar graph spacing consistent

components/custom/survey/graphs/AffordFairhold.tsx, components/custom/survey/graphs/Age.tsx, components/custom/survey/graphs/Country.tsx, components/custom/survey/graphs/SupportDevelopment.tsx, components/custom/survey/graphs/SupportNewFairhold.tsx, lib/survey/constants.tsx
Aligns labels left as per design (I had some trouble with switching the layout to vertical, we may need a custom component here if we want to render the `Legend` outside of the chart itself--depends on how closely we want to follow the designs.) Also shortened some labels to get them to fit! 
Before:
After:
=> style: doughnut legend fixes

app/survey/page.tsx, components/custom/survey/SurveyGraphCard.tsx
Aligns `h2` vertically in between `SurveyGraphCard`, aligns leftmost `SurveyGraphCard` left with `h2`, makes the padding around `SurveyGraphCard` titles consistent / even. 
Before: 
After:
=> style: fix survey label and card alignment

app/survey/page.tsx, components/custom/survey/SurveyGraphCard.tsx, components/custom/survey/graphs/SupportDevelopment.tsx, components/custom/survey/graphs/SupportNewFairhold.tsx
Adjusting margins and heights to ensure that all graphs render correctly in mobile, and that alignment and spacing are in line with designs. 
Before:
After:
Closes #624
=> feat: responsive styles for survey results

components/custom/survey/CustomSankey.tsx
Swaps text anchor (start and end) and adjusts sankey margin.
Before:
After:
=> style: justify sankey labels to nodes

components/custom/survey/CustomSankey.tsx, components/custom/survey/graphs/CurrentMeansTenureChoice.tsx, components/custom/survey/graphs/IdealHouseType.tsx, components/custom/survey/graphs/IdealLiveWith.tsx, lib/survey/constants.tsx, lib/survey/types.tsx, lib/survey/utils.tsx
Updated to maintain separation of concerns / handle all data management in backend and only visualisation in frontend. 
- Creates label mapping objects in `constants.tsx`
- Adds new `label` prop to `SankeyResult` and `applySankeyNodeLabels()` utility function
- Runs `applySankeyNodeLabels()` in `aggregateResults()`, returning labeled nodes to frontend
While doing this I realised the same pattern should be applied to the node colour handling too, so have branched off and opened #648 too (separated them as they're different concerns!) 
Before:
After:
=> feat: format sankey labels where needed

components/custom/survey/SurveyGraphCard.tsx, components/custom/survey/graphs/AffordFairhold.tsx, components/custom/survey/graphs/Age.tsx, components/custom/survey/graphs/AnyMeansTenureChoice.tsx, components/custom/survey/graphs/Country.tsx, components/custom/survey/graphs/HousingOutcomes.tsx, components/custom/survey/graphs/SupportDevelopment.tsx, components/custom/survey/graphs/SupportDevelopmentFactors.tsx, components/custom/survey/graphs/SupportNewFairhold.tsx, components/custom/survey/graphs/WhyFairhold.tsx, components/custom/survey/graphs/WhyNotFairhold.tsx, hooks/UseAnimateOnView.tsx, package-lock.json, package.json
- Installs `react-intersection-observer` dependency
- Creates new `useAnimateOnView` hook using `useInView`
- Uses hook in all survey results doughnut graphs
To animate on view and not on load, for a slightly nicer UX / fancy touch ✨ 
Closes #617
=> feat: animate on view, not load
