theopensystemslab/fairhold-dashboard

prisma/migrations/20241212122823_rename_prices_paid_table_and_columns/migration.sql
prisma/migrations/20241212123044_rename_prices_paid_constraint/migration.sql
prisma/migrations/20241212123358_make_prices_paid_fields_required/migration.sql
prisma/schema.prisma

Changes table and column names to Postgres convention snake_case for the `prices_paid` table
Makes fields required
Basically follows #162!

feat: rename `prices_paid` table

---

app/components/ui/CalculatorInput.tsx

It fixes the error #202 .
It sets the value of the Input component to an empty string should this not be set by the url optional parameters

Fix new Next error (task #202)

---

app/api/route.test.ts
app/api/route.ts
app/components/ui/CalculatorInput.tsx
app/data/itlRepo.test.ts
app/data/itlRepo.ts
app/data/pricesPaidRepo.test.ts
app/data/pricesPaidRepo.ts
app/lib/exceptions.ts
app/models/testClasses.ts
app/services/calculationService.test.ts
app/services/calculationService.ts

- Follows on from #228
- Replaces the business logic with a simple query to the pre-computed table
- This can't actually be used or tested until #228 is merged and the data is populated on production

feat: Query new `PricesPaidSummary` model

---

app/components/ui/Footer.tsx
app/layout.tsx
app/page.tsx
app/webflow.css
next.config.mjs

- Copies stylesheet from webflow
- Copies HTML footer from webflow
- Replace `<img>` with Nextjs' `<Image>` and  a few other type fixes
https://github.com/user-attachments/assets/fec4c261-907a-42ed-995d-d267885403ea

feat: Copy Webflow footer

---

app/components/ui/CalculatorInput.tsx

Small type issue which is blocking builds - missed somewhere by me in a rebase somewhere sorry!

fix: Incorrect variable name after rebase

---

app/components/Dashboard/Cards/WhatDifference.tsx
app/components/ui/Dashboard.tsx
app/components/ui/GraphCard.tsx

As with #264, this isn't perfect in terms of styles but the layout is pretty close and we can have a pass over with font sizes/colours etc when a few more things come together 👌 
This does _not_ work on mobile - focusing on rough layout / content here at this stage over this.

feat: Initial setup of "what difference..." card (5/6)

---

app/components/Dashboard/Cards/WhatDifference.tsx
app/components/Dashboard/Cards/WhatWouldYouChoose.tsx
app/components/ui/Dashboard.tsx
app/components/ui/GraphCard.tsx

A little rough and ready (styles aren't perfect) but the content and functionality is all here. As with other PRs, links are currently empty.

feat: Setup final card

---

app/components/Dashboard/Cards/HowMuchFHCost.tsx
app/components/graphs/UpfrontComparisonBarChart.tsx
app/components/graphs/UpfrontComparisonWrapper.tsx
app/components/ui/Dashboard.tsx
app/globals.css
components/ui/card.tsx
components/ui/chart.tsx
components/ui/label.tsx
package-lock.json
package.json

It uses shadcn library to generate the plot for the cumulative value of land and house for freehold, fairhold land purchase and fairhold land rent.
The styling needs updating to better match the [Miro layout](https://miro.com/app/board/uXjVLfGBUx4=/?moveToWidget=3458764601237935883&cot=14).
https://github.com/user-attachments/assets/af330606-8478-49f5-a082-452eb83255f2

feat: How much would Fairhold cost graph

---

app/components/ui/Carousel.tsx
app/components/ui/Dashboard.tsx

- Splits `Carousel` into its own component
- Adds scroll up and scroll down icons
- Adds page indicators
https://github.com/user-attachments/assets/82119fb7-5bad-454a-86da-bd9eac10c20f

feat: Scroll page indicator

---

app/components/graphs/UpfrontComparisonBarChart.tsx
app/lib/format.ts

feat: Add labels to bar chart

---

app/globals.css

Overwritten at some point earlier this week (sorry @gabrielegranello !!)

chore: Restore background colour

---

app/api/route.test.ts
app/api/route.ts
app/components/ui/CalculatorInput.tsx
app/globals.css
app/models/calculateFairhold.ts
app/schemas/calculationSchema.ts
app/schemas/formSchema.ts

It allows to treat the floor area as optional.
By two steps:
1) In the form validation schema, we allow to submit an empty string. If empty, the associated value will be null
2) In the calculation schema, if the value is empty, we apply the mapping function
I had to explicitly tell zod:
.transform((val) => (val === "" ? undefined : Number(val)))
how do deal with an empty string because it did not like the case where first a negative number was inserted, and then submitted with empty string.

feat: optional floor area

---

app/services/calculationService.test.ts
app/services/calculationService.ts

I don't know why this wasn't caught in #351 but just pushing this tiny fix so API tests will pass on other PRs

fix: calculationService GDHI test

---

app/components/Dashboard/Help/CostOverTime.md
app/components/Dashboard/Help/HowMuchFHCost.md
app/components/Dashboard/Help/HowMuchPerMonth.md
app/components/Dashboard/Help/ResaleValue.md
app/components/Dashboard/Help/WhatDifference.md

Link 'help text' to new [wiki](https://github.com/theopensystemslab/fairhold-dashboard/wiki) with more detailed docs

feat: add wiki links

---

app/components/ui/CalculatorInput.tsx

As discussed at roadmap today (since flats will be more common and also data more accurate than detached)

feat: re-order property types

---

app/components/ui/CalculatorInput.tsx

feat: remove house size input

---

app/components/Dashboard/Cards/HowMuchFHCost.tsx
app/components/Dashboard/Cards/HowMuchPerMonth.tsx

Noticed that other titles were written in the first person and other subtitles didn't have full stops

feat: consistent title and subtitle copy

---

app/components/Dashboard/Help/WhatDifference.md
app/components/ui/Drawer.tsx

- Enables scrolling in drawers
- Aligns title and description left on mobile
- Fixes a typo
Closes #391

fix: drawer formatting

---

app/components/ui/GraphCard.tsx

Lighter font weight, according to designs
Closes #420

feat: style graph subtitle weight

---

app/components/ui/Carousel.tsx

Restyles carousel button, according to new designs!
Closes #408

feat: restyle next button in carousel

---

app/components/ui/CalculatorInput.tsx

Before:
After:
As per designs:

feat: wider form

---

app/components/Dashboard/Cards/WhatDifference.tsx

I think the recategorisation makes more sense conceptually, but that it looks weird. What do others think?

feat: recategorise social value impacts

---

app/components/Dashboard/Cards/WhatWouldYouChoose.tsx

What do we think?
https://github.com/user-attachments/assets/ff2c3d1b-3235-4da1-845b-16eb841d43c8

feat: highlight survey button

---

app/components/ui/GraphCard.tsx
app/page.tsx

What do people make of scroll behaviour now? Please check on desktop and mobile, of course, using Preview link below!
Closes #411

feat: header

---

app/survey/components/graphs/SupportDevelopment.tsx
app/survey/components/graphs/SupportDevelopmentFactors.tsx
app/survey/components/graphs/SupportNewFairhold.tsx
app/survey/types.tsx

Placeholder graphs for the development attitudes section

feat: graphs for development section

---

app/globals.css
app/survey/components/graphs/Age.tsx
app/survey/components/graphs/Country.tsx
app/survey/components/graphs/SupportDevelopment.tsx
app/survey/components/graphs/SupportDevelopmentFactors.tsx
app/survey/components/graphs/SupportNewFairhold.tsx
app/survey/page.tsx
app/survey/types.tsx

First graphs for the "Who has respondent" section, with placeholder colours. Commented out the postcode graph for now because it's TBC.

feat: respondent section 

---

app/data/db.test.ts
app/data/pricesPaidRepo.test.ts
app/schemas/calculationSchema.ts
app/services/calculationService.test.ts

Our test coverage for branches keeps dropping weirdly. This PR adds some tests (and makes a couple code changes) to boost coverage again, hopefully fixing some CI.

chore: improve test coverage

---

app/survey/components/graphs/AffordFairhold.tsx
app/survey/components/graphs/Age.tsx
app/survey/components/graphs/Country.tsx
app/survey/components/graphs/SupportDevelopment.tsx
app/survey/components/graphs/SupportNewFairhold.tsx

Changes pie charts to doughnuts as per Alastair's request!

feat: pie charts to doughnuts

---

app/survey/components/graphs/WhyFairhold.tsx
app/survey/components/graphs/WhyNotFairhold.tsx
app/survey/page.tsx

These graphs were missing before!

feat: add "Why" or "Why not" Fairhold graphs

---

README.md
app/components/ui/Header.tsx
app/globals.css
app/page.tsx
app/survey/components/CustomSankey.tsx
app/survey/components/SurveyGraphCard.tsx
app/survey/components/graphs/AffordFairhold.tsx
app/survey/components/graphs/Age.tsx
app/survey/components/graphs/Country.tsx
app/survey/components/graphs/SupportDevelopment.tsx
app/survey/components/graphs/SupportDevelopmentFactors.tsx
app/survey/components/graphs/SupportNewFairhold.tsx
app/survey/constants.tsx
app/survey/page.tsx
app/survey/utils.tsx

Moved `Header` into `components/` to share with survey results.

feat: add footer to survey results

---

schemas/formSchema.ts

It allows for house age equal to 0. Closes #590

fix house built New option bug

---

components/custom/ui/InputDropdown.tsx

changed the classname attributes in the dropdown react component
https://github.com/user-attachments/assets/077e0944-80f0-4b67-a7a4-5db3b8fa59b5

Fix hover in the house built tab

---

components/custom/survey/graphs/AnyMeansTenureChoice.tsx

I put the animated bar graphs in a separate branch / PR so it'd be easier to preview and compare the two. 
This just applies the changes in #635 to bar graphs too.

feat: animate bar graphs too
